if vim.g.colors_name then
  vim.cmd.hi("clear")
else
end
vim.g["colors_name"] = "whiteboard"
vim.o["termguicolors"] = true
local palette = {bg = "#f5f0e0", base01 = "#d5c9b9", base02 = "#b5a999", fg = "#000000", base04 = "#554939", base05 = "#554939", base06 = "#525252", cyan = "#267459", magenta = "#A02a9a", red = "#A80011", yellow = "#986908", blue = "#0f428e", purple = "#5a1083", green = "#107300", orange = "#d65100", pink = "#d446bb", blend = "#d5c9b9", none = "NONE"}
vim.g["terminal_color_0"] = palette.base01
vim.g["terminal_color_1"] = palette.red
vim.g["terminal_color_2"] = palette.green
vim.g["terminal_color_3"] = palette.yellow
vim.g["terminal_color_4"] = palette.blue
vim.g["terminal_color_5"] = palette.magenta
vim.g["terminal_color_6"] = palette.cyan
vim.g["terminal_color_7"] = palette.base02
vim.g["terminal_color_8"] = palette.fg
vim.g["terminal_color_9"] = palette.red
vim.g["terminal_color_10"] = palette.green
vim.g["terminal_color_11"] = palette.yellow
vim.g["terminal_color_12"] = palette.blue
vim.g["terminal_color_13"] = palette.magenta
vim.g["terminal_color_14"] = palette.cyan
vim.g["terminal_color_15"] = palette.base04
vim.api.nvim_set_hl(0, "ColorColumn", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "Cursor", {fg = palette.bg, bg = palette.base04})
vim.api.nvim_set_hl(0, "CursorLine", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "CursorColumn", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "QuickFixLine", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "Error", {fg = palette.yellow, bg = palette.base01})
vim.api.nvim_set_hl(0, "LineNr", {fg = palette.fg, bg = palette.bg})
vim.api.nvim_set_hl(0, "NonText", {fg = palette.base02, bg = palette.none})
vim.api.nvim_set_hl(0, "Normal", {fg = palette.fg, bg = palette.bg})
vim.api.nvim_set_hl(0, "Pmenu", {fg = palette.base04, bg = palette.base01})
vim.api.nvim_set_hl(0, "PmenuSbar", {fg = palette.base04, bg = palette.base01})
vim.api.nvim_set_hl(0, "PmenuSel", {fg = palette.blue, bg = palette.base02})
vim.api.nvim_set_hl(0, "PmenuThumb", {fg = palette.blue, bg = palette.base02})
vim.api.nvim_set_hl(0, "SpecialKey", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "Visual", {fg = palette.none, bg = palette.base02})
vim.api.nvim_set_hl(0, "VisualNOS", {fg = palette.none, bg = palette.base02})
vim.api.nvim_set_hl(0, "TooLong", {fg = palette.none, bg = palette.base02})
vim.api.nvim_set_hl(0, "Debug", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "Macro", {fg = palette.yellow, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "MatchParen", {fg = palette.none, bg = palette.base02, underline = true})
vim.api.nvim_set_hl(0, "Bold", {fg = palette.none, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "Italic", {fg = palette.none, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "Underlined", {fg = palette.none, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "DiagnosticError", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = palette.cyan, bg = palette.none})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = palette.blue, bg = palette.none})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {fg = palette.base1, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {fg = palette.red, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {fg = palette.cyan, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {fg = palette.blue, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "HealthError", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "HealthWarning", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "HealthSuccess", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@text.literal.commodity", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "@number", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.date", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.date.effective", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.interval", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.status", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.quantity", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@number.quantity.negative", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "LspCodeLens", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "LspReferenceText", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "LspReferenceread", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "@lsp.type.class", {fg = palette.cyan, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "Decorator"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator.markdown", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.function", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.macro", {link = "Macro"})
vim.api.nvim_set_hl(0, "@lsp.type.method", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.struct", {fg = palette.cyan, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@lsp.type.type", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", {link = "Typedef"})
vim.api.nvim_set_hl(0, "@lsp.type.selfParameter", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinConstant", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.magicFunction", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "@boolean"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "@comment"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "Type", italic = true})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "@string.escape"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "@punctuation.special"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "@namespace"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "@number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "@property"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.string.rust", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "@type.definition"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {link = "Error"})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.mod.readonly", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.mod.typeHint", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.mod.builtin", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "@keyword.coroutine"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.controlFlow", {link = "@exception"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.documentation", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.global", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.builtin", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.readonly", {link = "@method"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "@variable"})
vim.api.nvim_set_hl(0, "Folded", {fg = palette.base02, bg = palette.base01})
vim.api.nvim_set_hl(0, "FoldColumn", {fg = palette.base01, bg = palette.bg})
vim.api.nvim_set_hl(0, "SignColumn", {fg = palette.base01, bg = palette.bg})
vim.api.nvim_set_hl(0, "Directory", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = palette.base01, bg = palette.none})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "Question", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "Substitute", {fg = palette.base01, bg = palette.magenta})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "WildMenu", {fg = palette.magenta, bg = palette.base01})
vim.api.nvim_set_hl(0, "helpHyperTextJump", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "helpSpecial", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "helpHeadline", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "helpHeader", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "DiffAdded", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "DiffChanged", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "DiffRemoved", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = palette.green, fg = palette.bg})
vim.api.nvim_set_hl(0, "DiffChange", {bg = palette.yellow, fg = palette.bg})
vim.api.nvim_set_hl(0, "DiffText", {bg = palette.blue, fg = palette.bg})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = palette.red, fg = palette.bg})
vim.api.nvim_set_hl(0, "IncSearch", {fg = palette.base06, bg = palette.yellow})
vim.api.nvim_set_hl(0, "Search", {fg = palette.base01, bg = palette.magenta})
vim.api.nvim_set_hl(0, "TabLine", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "TabLineFill", {link = "TabLine"})
vim.api.nvim_set_hl(0, "TabLineSel", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "Title", {fg = palette.green, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "VertSplit", {fg = palette.base01, bg = palette.bg})
vim.api.nvim_set_hl(0, "WinSeparator", {fg = palette.base01, bg = palette.bg})
vim.api.nvim_set_hl(0, "Boolean", {fg = palette.magenta, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "Character", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "Comment", {fg = palette.base05, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "Conceal", {fg = palette.none, bg = palette.none})
vim.api.nvim_set_hl(0, "Conditional", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Constant", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "Decorator", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "Define", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Delimeter", {fg = palette.base06, bg = palette.none})
vim.api.nvim_set_hl(0, "Exception", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "Float", {link = "Number"})
vim.api.nvim_set_hl(0, "Function", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "Identifier", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "Include", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Keyword", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Label", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Number", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "Operator", {fg = palette.orange, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "PreProc", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Repeat", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "Special", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "SpecialChar", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "SpecialComment", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "Statement", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "StorageClass", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "String", {fg = palette.blue, bg = palette.none})
vim.api.nvim_set_hl(0, "Structure", {fg = palette.cyan, bg = palette.none})
vim.api.nvim_set_hl(0, "Tag", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "Todo", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "Type", {fg = palette.cyan, bg = palette.none})
vim.api.nvim_set_hl(0, "Typedef", {fg = palette.purple, bg = palette.none})
vim.api.nvim_set_hl(0, "markdownBlockquote", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "markdownBold", {link = "Bold"})
vim.api.nvim_set_hl(0, "markdownItalic", {link = "Italic"})
vim.api.nvim_set_hl(0, "markdownBoldItalic", {fg = palette.none, bg = palette.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "markdownRule", {link = "Comment"})
vim.api.nvim_set_hl(0, "markdownH1", {fg = palette.blue, bg = palette.none})
vim.api.nvim_set_hl(0, "markdownH2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingRule", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownUrl", {fg = palette.orange, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "markdownCode", {link = "String"})
vim.api.nvim_set_hl(0, "markdownCodeBlock", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownUrl", {link = "String"})
vim.api.nvim_set_hl(0, "markdownListMarker", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "markdownOrderedListMarker", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "@markup", {link = "@none"})
vim.api.nvim_set_hl(0, "@markup.environment", {link = "Macro"})
vim.api.nvim_set_hl(0, "@markup.environment.name", {link = "Type"})
vim.api.nvim_set_hl(0, "@markup.emphasis", {italic = true})
vim.api.nvim_set_hl(0, "@markup.italic", {italic = true})
vim.api.nvim_set_hl(0, "@markup.strikethrough", {strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.strong", {bold = true})
vim.api.nvim_set_hl(0, "@markup.underline", {underline = true})
vim.api.nvim_set_hl(0, "@markup.heading", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.heading.marker", {link = "markdownHeadingDelimiter"})
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.7.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.8.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.link", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.label", {underline = true})
vim.api.nvim_set_hl(0, "@markup.link.label.symbol", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.label.markdown_inline", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.title", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.link.url", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.destination", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.description", {fg = palette.blend, underline = true, italic = true})
vim.api.nvim_set_hl(0, "@markup.list", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.bullet", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.checked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.markdown", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.ordered", {link = "markdownOrderedListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.unchecked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.math", {link = "Special"})
vim.api.nvim_set_hl(0, "@markup.raw", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.quote", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "@markup.literal", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "@markup.code.block", {link = "markdownCodeBlock"})
vim.api.nvim_set_hl(0, "@markup.rule", {link = "Comment"})
vim.api.nvim_set_hl(0, "asciidocAttributeEntry", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "asciidocAttributeList", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocAttributeRef", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocHLabel", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocOneLineTitle", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocQuotedMonospaced", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "asciidocURL", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@error", {fg = palette.blue, bg = palette.none})
vim.api.nvim_set_hl(0, "@operator", {link = "Operator"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {fg = palette.base06, bg = palette.none})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {fg = palette.base06, bg = palette.none})
vim.api.nvim_set_hl(0, "@punctuation.special", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "@string", {link = "String"})
vim.api.nvim_set_hl(0, "@string.regex", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "@string.escape", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "@character", {link = "Character"})
vim.api.nvim_set_hl(0, "@boolean", {link = "Boolean"})
vim.api.nvim_set_hl(0, "@number", {link = "Number"})
vim.api.nvim_set_hl(0, "@float", {link = "Float"})
vim.api.nvim_set_hl(0, "@function", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "@function.builtin", {fg = palette.yellow, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@function.macro", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "@method", {fg = palette.cyan, bg = palette.none})
vim.api.nvim_set_hl(0, "@constructor", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@parameter", {fg = palette.fg, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "@keyword", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@keyword.function", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@keyword.operator", {fg = palette.orange, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@conditional", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@repeat", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@label", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@include", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@exception", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "@type", {link = "Type"})
vim.api.nvim_set_hl(0, "@type.builtin", {link = "Type"})
vim.api.nvim_set_hl(0, "@attribute", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@field", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@property", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@variable", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@variable.builtin", {fg = palette.fg, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@constant", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@constant.builtin", {fg = palette.fg, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "@constant.macro", {fg = palette.cyan, bg = palette.none})
vim.api.nvim_set_hl(0, "@namespace", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@symbol", {fg = palette.pink, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "@text", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "@text.strong", {fg = palette.none, bg = palette.none})
vim.api.nvim_set_hl(0, "@text.emphasis", {fg = palette.yellow, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "@text.underline", {fg = palette.yellow, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "@text.strike", {fg = palette.yellow, bg = palette.none, strikethrough = true})
vim.api.nvim_set_hl(0, "@text.title", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "@text.literal", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "@text.uri", {fg = palette.orange, bg = palette.none, underline = true})
vim.api.nvim_set_hl(0, "@tag", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "@tag.attribute", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@tag.delimiter", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "@tag.builtin.tsx", {link = "@tag.tsx"})
vim.api.nvim_set_hl(0, "@spell.markdown", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "@reference", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimInternalError", {fg = palette.bg, bg = palette.magenta})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = palette.base05, bg = palette.blend})
vim.api.nvim_set_hl(0, "FloatBorder", {fg = palette.blend, bg = palette.blend})
vim.api.nvim_set_hl(0, "NormalNC", {fg = palette.base04, bg = palette.bg})
vim.api.nvim_set_hl(0, "TermCursor", {fg = palette.bg, bg = palette.base04})
vim.api.nvim_set_hl(0, "TermCursorNC", {fg = palette.bg, bg = palette.base04})
vim.api.nvim_set_hl(0, "StatusLine", {fg = palette.base04, bg = palette.bg})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg = palette.base04, bg = palette.base01})
vim.api.nvim_set_hl(0, "StatusReplace", {fg = palette.bg, bg = palette.magenta})
vim.api.nvim_set_hl(0, "StatusInsert", {fg = palette.bg, bg = palette.purple})
vim.api.nvim_set_hl(0, "StatusVisual", {fg = palette.bg, bg = palette.orange})
vim.api.nvim_set_hl(0, "StatusTerminal", {fg = palette.bg, bg = palette.blue})
vim.api.nvim_set_hl(0, "StatusNormal", {fg = palette.bg, bg = palette.pink})
vim.api.nvim_set_hl(0, "StatusCommand", {fg = palette.bg, bg = palette.green})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticWarn", {fg = palette.yellow, bg = palette.bg, bold = true})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticError", {fg = palette.red, bg = palette.bg, bold = true})
vim.api.nvim_set_hl(0, "TelescopeBorder", {fg = palette.blend, bg = palette.blend})
vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg = palette.base02, bg = palette.base02})
vim.api.nvim_set_hl(0, "TelescopePromptNormal", {fg = palette.base05, bg = palette.base02})
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg = palette.magenta, bg = palette.base02})
vim.api.nvim_set_hl(0, "TelescopeNormal", {fg = palette.none, bg = palette.blend})
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", {fg = palette.base02, bg = palette.purple})
vim.api.nvim_set_hl(0, "TelescopePromptTitle", {fg = palette.base02, bg = palette.blue})
vim.api.nvim_set_hl(0, "TelescopeResultsTitle", {fg = palette.blend, bg = palette.blend})
vim.api.nvim_set_hl(0, "TelescopeSelection", {fg = palette.none, bg = palette.base02})
vim.api.nvim_set_hl(0, "TelescopePreviewLine", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "TelescopeMatching", {fg = palette.magenta, bg = palette.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg = palette.base05, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg = palette.base05, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg = palette.orange, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg = palette.base05, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "NotifyTRACETitle", {fg = palette.green, bg = palette.none})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#adadad", bg = palette.none})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg = palette.red, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = palette.base04, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemMenu", {fg = palette.base04, bg = palette.none, italic = true})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg = palette.base01, bg = palette.magenta})
vim.api.nvim_set_hl(0, "CmpItemKindColor", {fg = palette.base01, bg = palette.magenta})
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg = palette.base01, bg = palette.magenta})
vim.api.nvim_set_hl(0, "CmpItemKindText", {fg = palette.base01, bg = palette.red})
vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg = palette.base01, bg = palette.red})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = palette.base01, bg = palette.red})
vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg = palette.base01, bg = palette.yellow})
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg = palette.base01, bg = palette.yellow})
vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg = palette.base01, bg = palette.yellow})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg = palette.base01, bg = palette.blue})
vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg = palette.base01, bg = palette.blue})
vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg = palette.base01, bg = palette.blue})
vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg = palette.base01, bg = palette.blue})
vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg = palette.base01, bg = palette.blue})
vim.api.nvim_set_hl(0, "CmpItemKindField", {fg = palette.base01, bg = palette.purple})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg = palette.base01, bg = palette.purple})
vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg = palette.base01, bg = palette.purple})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg = palette.base01, bg = palette.green})
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg = palette.base01, bg = palette.green})
vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg = palette.base01, bg = palette.green})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = palette.base01, bg = palette.orange})
vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg = palette.base01, bg = palette.orange})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = palette.base01, bg = palette.pink})
vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg = palette.base01, bg = palette.pink})
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg = palette.base01, bg = palette.pink})
vim.api.nvim_set_hl(0, "NvimTreeImageFile", {fg = palette.purple, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {fg = palette.purple, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {fg = palette.bg, bg = palette.base00})
vim.api.nvim_set_hl(0, "NvimTreeFolderName", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {fg = palette.base02, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {fg = palette.pink, bg = palette.none})
vim.api.nvim_set_hl(0, "NvimTreeNormal", {fg = palette.base04, bg = palette.bg})
vim.api.nvim_set_hl(0, "NeogitBranch", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "NeogitRemote", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "NeogitHunkHeader", {fg = palette.base04, bg = palette.base02})
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", {fg = palette.base04, bg = palette.fg})
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", {link = "Comment"})
vim.api.nvim_set_hl(0, "HydraRed", {fg = palette.purple, bg = palette.none})
vim.api.nvim_set_hl(0, "HydraBlue", {fg = palette.red, bg = palette.none})
vim.api.nvim_set_hl(0, "HydraAmaranth", {fg = palette.yellow, bg = palette.none})
vim.api.nvim_set_hl(0, "HydraTeal", {fg = palette.magenta, bg = palette.none})
vim.api.nvim_set_hl(0, "HydraHint", {fg = palette.none, bg = palette.blend})
vim.api.nvim_set_hl(0, "alpha1", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "alpha2", {fg = palette.base04, bg = palette.none})
vim.api.nvim_set_hl(0, "alpha3", {fg = palette.fg, bg = palette.none})
vim.api.nvim_set_hl(0, "CodeBlock", {fg = palette.none, bg = palette.base01})
vim.api.nvim_set_hl(0, "BufferLineDiagnostic", {fg = palette.yellow, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "BufferLineDiagnosticVisible", {fg = palette.yellow, bg = palette.none, bold = true})
vim.api.nvim_set_hl(0, "htmlH1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "mkdRule", {link = "markdownRule"})
vim.api.nvim_set_hl(0, "mkdListItem", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "mkdListItemCheckbox", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiHeader1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeaderChar", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiList", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiLink", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "VimwikiCode", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "FlashLabel", {fg = palette.magenta, bg = palette.bg, bold = true})
vim.api.nvim_set_hl(0, "@org.keyword.todo", {fg = palette.red, bg = palette.bg})
vim.api.nvim_set_hl(0, "@org.keyword.todo", {fg = palette.red, bg = palette.bg})
vim.api.nvim_set_hl(0, "@org.headline.level2", {fg = palette.red, bg = palette.bg})
return {palette = palette}
